#define MICROPY_HW_BOARD_NAME "GOOUUU-ESP32S3-CAM"
#define MICROPY_HW_MCU_NAME "ESP32S3"
#define MICROPY_CAMERA_MODEL_ESP32S3_EYE 1
#define MICROPY_HW_SDCARD_SDMMC 1
#define MICROPY_HW_SDCARD_SLOT 1
#define MICROPY_HW_SDMMC_CLK 39
#define MICROPY_HW_SDMMC_CMD 38
#define MICROPY_HW_SDMMC_D0 40
